apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: multi-container-app
  ports:
  - protocol: TCP
    port: 80       # Порт, на котором сервис будет доступен внутри кластера
    targetPort: 80 # Порт контейнера nginx
    nodePort: 30001 # Порт, на котором будет доступен сервис снаружи (можно выбрать любой порт в диапазоне 30000-32767)